export class Constants {
  static DAYS_OF_WEEK: string[] = [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday'
  ];

  // Dictionary of CSV column indices to organization fields.
  static CSV_ORG_FIELD_DICT = {
    name: 0,
    description: 1,
    streetAddress1: 2,
    streetAddress2: 3,
    city: 4,
    state: 5,
    zipCode: 6,
    contactName: 7,
    phone: 8,
    email: 9,
    website: 10,
    specifyHours: 11,
    sundayStart: 12,
    sundayEnd: 13,
    mondayStart: 14,
    mondayEnd: 15,
    tuesdayStart: 16,
    tuesdayEnd: 17,
    wednesdayStart: 18,
    wednesdayEnd: 19,
    thursdayStart: 20,
    thursdayEnd: 21,
    fridayStart: 22,
    fridayEnd: 23,
    saturdayStart: 24,
    saturdayEnd: 25,
    clothing: 26,
    medicalCare: 27,
    mentalHealth: 28,
    publicTransportation: 29,
    techSupport: 30,
    financialLiteracy: 31,
    substanceUse: 32,
    religiousOrganization: 33,
    housingSupport: 34,
    parenting: 35,
    volunteeringOpportunities: 36,
    legalAssistance: 37,
    publicBenefitAssistance: 38,
    employment: 39,
    education: 40,
    supportNetworksAndMentoring: 41,
    domesticViolenceSexualAssault: 42,
    payment: 43,
    transportation: 44,
    languages: 45,
    seniorRequirements: 46,
    eligibilityRequirements: 47,
    bringWithYou: 48,
    additionalNotes: 49
  };

  // Dictionary of CSV org service field to service name.
  static CSV_ORG_SERVICE_DICT = {
    clothing: 'Clothing',
    medicalCare: 'Medical Care',
    mentalHealth: 'Mental Health',
    publicTransportation: 'Public Transportation',
    techSupport: 'Tech Support',
    financialLiteracy: 'Financial Literacy',
    substanceUse: 'Substance Use',
    religiousOrganization: 'Religious Organization',
    housingSupport: 'Housing Support',
    parenting: 'Parenting',
    volunteeringOpportunities: 'Volunteering Opportunities',
    legalAssistance: 'Legal Assistance',
    publicBenefitAssistance: 'Public Benefit Assistance',
    employment: 'Employment',
    education: 'Education',
    supportNetworksAndMentoring: 'Support Networks And Mentoring',
    domesticViolenceSexualAssault: 'Domestic Violence/Sexual Assault'
  };
}
